<div class="row">
    <div class="col-lg-12">
        <!-- text-left -->
        <div class="text-left">
            <a href="/admin/picture-form/" class="request"> +Thêm hình ảnh </a>
        </div><br>
        <!-- Start widget table -->
        <?php $wg = array(
                        'title'  => array('Tên album', 'Caption', 'Hình ảnh', 'Ngày tạo'),
                        'col'    => array('name', 'caption', 'image', 'created'),
                        'source' => $data,
                        'link'   => array('/admin/picture-form/', '/admin/picture-delete/', '/admin/picture-list/')
                    ); ?>
        <?php Multiple\Backend\Plugins\Widget::load('table', $wg); ?>
        <!-- End widget table-->
    </div>
</div>
<!-- don't forget bind value for #pagetitle -->
<input type="hidden" id="pagetitle" value="<?php echo isset($title)?$title:'' ?>">