<form action="<?php echo $action ?>" method="POST" role="form" style="width: 50%; border: 1px solid #ddd; padding: 10px">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="">Tên album</label>
                <input type="text" class="form-control" name="name" value="<?php echo ($data) ? $data->name : '' ?>">
            </div>
        </div>
         <div class="col-md-6">
            <div class="form-group">
                <label for="">Alias</label>
                <input type="text" class="form-control" name="alias" value="<?php echo ($data) ? $data->alias : '' ?>">
            </div>
        </div>
    </div>
    <input type="hidden" name="id" value="<?php echo ($data) ? $data->id : '' ?>">
    <input type="hidden" name="created" value="<?php echo ($data) ? $data->created : date('Y-m-d') ?>">
    <input type="hidden" name="author" value="<?php echo ($data) ? $data->author : $userLogin['id'] ?>">
    <button type="submit" class="btn btn-default">Lưu lại</button>
</form>
<?php Multiple\Backend\Plugins\Widget::load('Alias', array('input'=>'name', 'alias'=>'alias')) ?>