<div class="row">
    <div class="col-lg-12">
        <!-- text-left -->
        <div class="text-left">
            <a href="/admin/album-form/" class="request"> +Thêm album </a>
        </div><br>
        <!-- Start widget table -->
        <?php $wg = array(
                        'title'  => array('Tên album', 'Alias', 'Tác giả album', 'Ngày tạo'),
                        'col'    => array('name', 'alias', 'author', 'created'),
                        'addCol' => array('colName'=>array('Xem album'), 'content'=>array('Xem chi tiết'=>'/albums/')),
                        'source' => $data,
                        'link'   => array('/admin/album-form/', '/admin/album-delete/', '/admin/album-list/')
                    ); ?>
        <?php Multiple\Backend\Plugins\Widget::load('table', $wg); ?>
        <!-- End widget table-->
    </div>
</div>
<!-- don't forget bind value for #pagetitle -->
<input type="hidden" id="pagetitle" value="<?php echo isset($title)?$title:'' ?>">